### ISSUE TITLE
Erro falha ao realizar login [FIX]

### ISSUE THREAD

**Issue by gabriel-roque** [gepittes/doafacil_old#17]

**Comment by jadilson12** [comment]
Isso já foi arrumado correto?

**Comment by gabriel-roque** [comment]
@jadilson12 Sim. Pode dar um close. Esqueci de dar close pelo commit

**Comment by jadilson12** [comment]
detalhe, quando é digitado a conta errada não está mostando a mensagem, está causando erro no console isso não é legal :)

**Comment by gabriel-roque** [comment]
@jadilson12 Nada que não vamos conseguir arrumar.

**Comment by gabriel-roque** [comment]
Solved in https://github.com/gepittes/doafacil/pull/23
