### ISSUE TITLE
[FIX] bloqued CORS quando user erra login na página inicial

### ISSUE THREAD

**Issue by gabriel-roque** [gepittes/doafacil_old#30]
Devera retornar um ALERT/ERROR informando erro de login.

**Comment by gabriel-roque** [comment]
@Pedro-Philipe Essa Issue aqui

**Comment by jadilson12** [comment]
@gabriel-roque esse

**Comment by jadilson12** [comment]
Para resolver esse erro, user esse comando

sudo chmod -R 777 api/storage/logs/
